DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sections CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS daily_darshan CASCADE;
DROP TABLE IF EXISTS overview_images CASCADE;
DROP TABLE IF EXISTS quotes CASCADE;

DROP FUNCTION IF EXISTS update_modified_column() CASCADE;